services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y libcairo2 libpango-1.0-0 libpangocairo-1.0-0 libgdk-pixbuf2.0-0
      pip install -r requirements.txt
    startCommand: gunicorn app:app
