"""Add is_blocked field to User model

Revision ID: 25a9fbda02c1
Revises: 54f6cf8c89ce
Create Date: 2025-04-27 01:46:41.869967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25a9fbda02c1'
down_revision = '54f6cf8c89ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_blocked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_blocked')

    # ### end Alembic commands ###
