"""Initial migration for settings and api key tables

Revision ID: abf0bcf8cd8e
Revises: 1d8c177fdbc3
Create Date: 2025-04-27 03:55:33.958248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abf0bcf8cd8e'
down_revision = '1d8c177fdbc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_name', sa.String(length=150), nullable=True),
    sa.Column('admin_email', sa.String(length=150), nullable=True),
    sa.Column('theme_color', sa.String(length=50), nullable=True),
    sa.Column('enable_registration', sa.Boolean(), nullable=True),
    sa.Column('logo_filename', sa.String(length=150), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
